In [25]:
import pandas as pd

In [26]:
mat=pd.read_pickle("./rinsetsu_matrix.pkl")

In [27]:
rinsetsu_matrix=pd.Series(mat).unstack()
rinsetsu_matrix.head()

,,&lt;script&gt;document.write&quot;&lt;style&gt;.afm{position,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,0.0.0.0,0.0.0.10,0.0.0.2,0000100.com,001lux.com,001www.com,003457.com,...,zxp.ca,zxspectrom.com,zxwyhg.com,zyclub.cn,zygj.cn,zyrenbbs.com,zyzq.cn,zzgdb.cn,zztuhao.com,zzwy8888.com
103.1.93.166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103.92.29.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104.49.63.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109.248.9.101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109.248.9.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
rinsetsu_describe = rinsetsu_matrix.T.describe()
for i in rinsetsu_describe:
    print(rinsetsu_describe[i]['mean'])

2.0
2.0
2.0
84896.0
86496.0
1113.8235294117646
497.0416666666667
246.76470588235293
641.5
287.25
2.0
2.0
6.0
2.0
4.0
318.1397058823529
24.42997491638796
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
948.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
10.0
1.5
2.0
2.0
2.0
4.0
38.0
2.0
2.0
2.0
2.0
1.5
1.5
1.5
432.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
8.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
886.0
2.0
2.0
2327.0
2092.0
1.0
2.628555955528655
30.842543077837195
73.31946508172362
112.64462809917356
29.027855153203344
79.38273921200751
128.80229885057472
13.69278792396571
27.245536571318873
11.448746454036648
30.893017628759072
95.5
21.136111111111113
391.5780346820809
12.480981595092025
70.75970425138632
72.4512
97.76674937965261
238.5505617977528
35.495789995047055
105.48327137546468
96.77826564215148
95.32978723404256
1009.0
2.0
2.0
674.0
1277.0
1335.0
2.0
12.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
1.5
2.0
2.0

In [13]:
rinsetsu_matrix_2 = pd.DataFrame(dtype='uint64')
rinsetsu_matrix_2 = rinsetsu_matrix.fillna(0)

In [18]:
import numpy as np
rinsetsu_matrix_2.astype(np.int64).to_csv('rinsetsu_matrix.csv')

In [39]:
rinsetsu_describe

,103.1.93.166,103.92.29.7,104.49.63.19,109.248.9.101,109.248.9.102,109.248.9.103,109.248.9.105,109.248.9.106,109.248.9.108,109.248.9.111,...,65.19.167.132,68.132.139.19,69.160.110.223,70.90.115.249,85.202.163.127,86.57.226.4,91.121.112.181,91.207.175.168,95.128.43.164,95.32.249.199
count,1.0,1.0,1.0,1.0,1.0,34.000000,24.000000,34.000000,6.000000,4.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,1.0,1.0
mean,2.0,2.0,2.0,84896.0,86496.0,1113.823529,497.041667,246.764706,641.500000,287.25,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.500000,2.0,2.0
std,NaN,NaN,NaN,NaN,NaN,3242.679097,2243.556328,454.739223,1014.969113,568.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.707107,NaN,NaN
min,2.0,2.0,2.0,84896.0,86496.0,2.000000,2.000000,2.000000,2.000000,3.00,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.000000,2.0,2.0
25%,2.0,2.0,2.0,84896.0,86496.0,6.000000,4.000000,8.250000,12.500000,3.00,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.250000,2.0,2.0
50%,2.0,2.0,2.0,84896.0,86496.0,37.000000,8.000000,39.000000,104.500000,3.00,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.500000,2.0,2.0
75%,2.0,2.0,2.0,84896.0,86496.0,558.500000,31.000000,192.000000,876.750000,287.25,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.750000,2.0,2.0
max,2.0,2.0,2.0,84896.0,86496.0,13709.000000,11025.000000,1945.000000,2522.000000,1140.00,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.000000,2.0,2.0

In [48]:
import json
def highspeed_load_command_info():
    path_r = "train/logdata2-5_command_hist_highspeed.json"
    with open(path_r) as fp:
        command_info = json.loads(fp.read())
    return command_info

In [49]:
command_info = highspeed_load_command_info()

In [54]:
import pandas as pd
import numpy as np
infooo = np.array(command_info['D_array'])
#infooo = pd.DataFrame(command_info['D_array'])
infooo

array([0.96012739, 0.78306954, 1.        , ..., 0.83987185, 0.69230769,
       0.35948738])

In [75]:
import scipy
from scipy.spatial.distance import pdist
from scipy.cluster.hierarchy import linkage
from sklearn.metrics.pairwise import cosine_similarity
from scipy.cluster.hierarchy import dendrogram
from sklearn.feature_extraction.text import CountVectorizer

def create_X_array_and_command_list():
    path_r = "train/logdata2-5_command_hist.json"
    with open(path_r) as fp:
        command_history = json.loads(fp.read())

    command_list = []
    for key in command_history:
        command_str = " ".join(command_history[key]["command"])
        if command_str not in command_list:
            command_list.append(command_str)
    #外れ値の除去
    command_list.pop(19)
    vectorizer = CountVectorizer()
    X = vectorizer.fit_transform(command_list)
    X_array = X.toarray()
    D_array = pdist(X_array, metric = 'cosine')
    return X, X_array, D_array

In [76]:
X, X_array, D_array = create_X_array_and_command_list()

In [85]:
print(len(X_array))
print(len(D_array))
X

133
8778

<133x278 sparse matrix of type '<class 'numpy.int64'>'
	with 1068 stored elements in Compressed Sparse Row format>

In [86]:
import numpy as np
from scipy.spatial import distance

dist_M = distance.cdist(X_array, X_array, metric='cosine')

In [90]:
dist_M

array([[0.00000000e+00, 9.60127389e-01, 7.83069542e-01, ...,
        7.98198162e-01, 8.59971992e-01, 7.98198162e-01],
       [9.60127389e-01, 0.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [7.83069542e-01, 1.00000000e+00, 2.22044605e-16, ...,
        8.75965265e-01, 1.00000000e+00, 8.75965265e-01],
       ...,
       [7.98198162e-01, 1.00000000e+00, 8.75965265e-01, ...,
        0.00000000e+00, 8.39871846e-01, 6.92307692e-01],
       [8.59971992e-01, 1.00000000e+00, 1.00000000e+00, ...,
        8.39871846e-01, 0.00000000e+00, 3.59487385e-01],
       [7.98198162e-01, 1.00000000e+00, 8.75965265e-01, ...,
        6.92307692e-01, 3.59487385e-01, 0.00000000e+00]])

In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform("")